routes.py
import json
import os
import requests
from flask import Blueprint, render_template, request, jsonify
import config
from db_conn import connect_db
import logger as D
import win32api
import win32print

# Crear un Blueprint para las rutas
app_blueprint = Blueprint("app_blueprint", __name__)

@app_blueprint.route("/")
def index():
    D.info("Cargando pagina inicial")
    return render_template(
        "home.html",
            LOGS=config.LOGS,
            PATH=config.PATH,
            PLATFORM=config.PLATFORM,
            VERSION=config.VERSION,
            CONFIG_PATH=config.CONFIG_PATH,
    )

# Ruta para obtener informacion sobre la plataforma
@app_blueprint.route("/management/home")
def home():
    D.info("Cargando informacion")
    try:
        response = requests.get(config.BASE_URL)
        response.raise_for_status()
        return render_template(
            "home.html",
            LOGS=config.LOGS,
            PATH=config.PATH,
            PLATFORM=config.PLATFORM,
            VERSION=config.VERSION,
            CONFIG_PATH=config.CONFIG_PATH,
        )
    except requests.exceptions.RequestException as e:
        D.error(f"Error: {str(e)}")
        return jsonify({"Error: Hubo un problema al cargar la página: ": str(e)}), 500

# Ruta para obtener informacion sobre la plataforma
@app_blueprint.route("/management/config")
def get_settings():
    D.info("Cargando configuracion")
    try:
        response = requests.get(config.BASE_URL)
        response.raise_for_status()
        with open(config.CONFIG_PATH, "r") as archive:
            printers_info = json.load(archive)
        return render_template(
            "config.html",
            printers=printers_info,
            config_dict=config.DICT
        )
    except requests.exceptions.RequestException as e:
        D.error(f"Error: {str(e)}")
        return jsonify({"Error: Hubo un problema al cargar la página: ": str(e)}), 500

@app_blueprint.route("/management/config", methods=["POST"])
def save_settings():
    try:
        D.info(f"Content-Type recibido: {request.content_type}")
        data = request.get_json()
        # Obtener valores del JSON recibido
        NOTIFY = str(data.get("NOTIFY"))
        NOTIFICATION = data.get("NOTIFICATION")
        EMAIL = data.get("EMAIL")
        PASSWORD = data.get("PASSWORD")
        PORT = data.get("PORT")
        HOST = data.get("HOST")
        TO = data.get("TO")
        CC = data.get("CC")
        SUBJECT = data.get("SUBJECT")
        PRINT_SC = data.get("PRINT_SC")
        TIME_SECONDS = data.get("TIME_SECONDS")
        USER_DB = data.get("USER_DB")
        PASSWORD_DB = data.get("PASSWORD_DB")
        SERVER = data.get("SERVER")
        DATABASE_DB = data.get("DATABASE_DB")

        
        required_fields = [
            NOTIFY, NOTIFICATION, EMAIL, PASSWORD, PORT, HOST, TO, CC, SUBJECT,
            PRINT_SC, TIME_SECONDS, USER_DB, PASSWORD_DB, SERVER, DATABASE_DB
        ]

        # Validar que todos los campos estén presentes
        if not all(required_fields):
            return jsonify({"Error": "Todos los campos deben ser completados."}), 400

        # Actualizar o agregar valores a la sección MAIL
        if "MAIL" not in config.CONFIG_PARSER:
            config.CONFIG_PARSER["MAIL"] = {}

        config.CONFIG_PARSER["MAIL"]["NOTIFY"] = NOTIFY
        config.CONFIG_PARSER["MAIL"]["NOTIFICATION"] = NOTIFICATION
        config.CONFIG_PARSER["MAIL"]["EMAIL"] = EMAIL
        config.CONFIG_PARSER["MAIL"]["PASSWORD"] = PASSWORD
        config.CONFIG_PARSER["MAIL"]["PORT"] = PORT
        config.CONFIG_PARSER["MAIL"]["HOST"] = HOST
        config.CONFIG_PARSER["MAIL"]["TO"] = TO
        config.CONFIG_PARSER["MAIL"]["CC"] = CC
        config.CONFIG_PARSER["MAIL"]["SUBJECT"] = SUBJECT

        # Actualizar o agregar valores a la sección PRINT_SETTINGS
        if "PRINT_SETTINGS" not in config.CONFIG_PARSER:
            config.CONFIG_PARSER["PRINT_SETTINGS"] = {}

        config.CONFIG_PARSER["PRINT_SETTINGS"]["PRINT_SC"] = PRINT_SC
        config.CONFIG_PARSER["PRINT_SETTINGS"]["TIME_SECONDS"] = str(TIME_SECONDS)

        # Actualizar o agregar valores a la sección BD
        if "BD" not in config.CONFIG_PARSER:
            config.CONFIG_PARSER["BD"] = {}

        config.CONFIG_PARSER["BD"]["USER_DB"] = USER_DB
        config.CONFIG_PARSER["BD"]["PASSWORD_DB"] = PASSWORD_DB
        config.CONFIG_PARSER["BD"]["SERVER"] = SERVER
        config.CONFIG_PARSER["BD"]["DATABASE_DB"] = DATABASE_DB

        # Guardar la configuración actualizada en el archivo settings.ini
        with open(config.SETTINGS_PATH, "w") as configfile:
            config.CONFIG_PARSER.write(configfile)
            config.CONFIG_PARSER.update()
            config.DICT = config.update_dict()

        try:
            connect_db()
        except Exception as e:
            return jsonify({"message": "Usuario o contraseña de la base de datos incorrectos", "Error": "Unauthorized","code": 401,}), 401
        return jsonify({"message": "Configuración guardada correctamente."}), 200

    except Exception as e:
        D.error(f"Error al guardar configuración: {str(e)}")
        return jsonify({"Error": f"Error al guardar configuración: {str(e)}"}), 500

# Ruta para cargar la pagina de impresion con las impresoras disponibles
@app_blueprint.route("/management/print")
def printer():
    D.info("Cargando pagina de impresion")
    try:
        # Lee la configuración de las impresoras desde config.json
        with open(config.CONFIG_PATH, "r") as archive:
            printers_info = json.load(archive)
        return render_template("print.html", printers=printers_info)
    except Exception as e:
        D.error(f"Error al obtener impresoras: {str(e)}")
        return jsonify({"Error al obtener impresoras:": str(e)}), 500

# Ruta para obtener las impresoras disponibles en el sistema
@app_blueprint.route("/printers", methods=["GET"])
def get_printers():
    D.info("Obteniendo impresoras del cliente")
    try:
        # Abre el archivo de configuración y lee las impresoras
        with open(config.CONFIG_PATH, "r") as archive:
            printers_info = json.load(archive)  # Carga la lista de impresoras del archivo de configuración
        
        # Devuelve la lista de impresoras en formato JSON
        if not printers_info:
            raise ValueError("No se encontraron impresoras en la configuración.")

        return jsonify(printers_info)
    except Exception as e:
        D.error(f"Error: {str(e)}")
        return jsonify({"Error": str(e)}), 500

@app_blueprint.route("/printers/<printer_id>", methods=["POST"])
def print_document(printer_id):
    try:
        hprinter = win32print.OpenPrinter(printer_id)

        # Obtiene el archivo y el numero de copias desde la solicitud
        file = request.files["file"]
        copies = int(
            request.form.get("copies", 1)
        )  # Valor predeterminado de 1 copia si no se especifica

        # Guarda el archivo en la carpeta temporal
        temp_folder = os.path.join(os.getcwd(), "temp")
        os.makedirs(temp_folder, exist_ok=True)
        file_path = os.path.join(temp_folder, file.filename)
        file.save(file_path)

        # Verifica que el archivo se haya guardado correctamente
        if not os.path.exists(file_path):
            return jsonify({"Error": "Archivo no encontrado"}), 400

        # Determina la extension del archivo para procesarlo adecuadamente
        file_extension = file.filename.rsplit(".", 1)[-1].lower()

        with open(file_path, "rb") as f:
            data = f.read()
            # Imprime el archivo la cantidad de veces indicada
            for _ in range(copies):
                try:
                    # Empieza un trabajo de impresion con el nombre del archivo
                    job_info = (
                        file.filename,
                        None,
                        "RAW",
                    )  # Usa el nombre real del archivo
                    win32print.StartDocPrinter(hprinter, 1, job_info)

                    try:
                        win32print.StartPagePrinter(hprinter)
                        win32print.WritePrinter(
                            hprinter, data
                        )  # Envia los datos a la impresora

                        win32print.EndPagePrinter(hprinter)
                    finally:
                        win32print.EndDocPrinter(hprinter)
                except Exception as e:
                    print(f"Error al imprimir: {e}")

        return jsonify({"message": "Documento enviado a imprimir"}), 200

    except Exception as e:
        return jsonify({"Error: No se ha podidoo enviar el archivo a imprimir": str(e)}), 500

templates/config.html
{% extends 'index.html' %} {% block title %} Configuración - eA3SC {% endblock
%} {% block content %}
<h1 class="title mt-2 text-center">Propiedades</h1>
<hr />
<form id="PropertiesForm">
  <div class="container">
    <div class="box-container">
      <!-- Tarjeta de Impresoras -->
      <div class="box">
        <h4 class="card-title">Impresoras</h4>
        <hr />
        <ul class="list-unstyled">
          <li class="mb-2 row g-2 align-items-center">
            <div class="col-4"><strong>Impresión SC:</strong></div>
            <div class="col-8">
              <select id="printerSelect" name="printer" class="form-select"
                required>
                <option value disabled selected>Seleccione una
                  impresora</option>
                {% for printer in available_printers %}
                <option value="{{ printer }}" {% if printer == config_dict['PRINT_SC'] %}selected{% endif %}>{{ printer }}</option>
                {% endfor %}
              </select>
            </div>
          </li>
          <li class="mb-2 row g-2 align-items-center">
            <div class="col-4"><strong>Tiempo en segundos:</strong></div>
            <div class="col-8">
              <input
                type="number"
                class="form-control"
                id="TIME_SECONDS"
                value="{{ config_dict['TIME_SECONDS'] }}"
                max="60"
                min="1" />
            </div>
          </li>
        </ul>
      </div>

      <!-- Tarjeta de Mail -->
      <div class="box">
        <h4 class="card-title">Mail</h4>
        <hr />
        <ul class="list-unstyled">
          <li class="mb-2 row g-2 align-items-center">
            <div class="col-4 ">
              <strong for="NOTIFY"> Notificar: </strong>
            </div>
            <div class="col-8">
              <div class="form-check form-switch">
                <input
                  class="form-check-input"
                  type="checkbox"
                  id="NOTIFY"
                  name="notify"
                  {% if config_dict['NOTIFY'] == 'True' %}checked{% endif %}
                />
              </div>
            </div>
          </li>
          <li class="mb-2 row g-2 align-items-center">
            <div class="col-4"><strong>Notificación:</strong></div>
            <div class="col-8">
              <input
                type="text"
                class="form-control"
                id="NOTIFICATION"
                value="{{ config_dict['NOTIFICATION'] }}"
                max="60"
                min="1" 
                disabled
                />
            </div>
          </li>

          <hr />
          {% for key in ['EMAIL', 'PASSWORD', 'PORT', 'HOST', 'TO', 'CC',
          'SUBJECT'] %}
          <li class="mb-2 row g-2 align-items-center">
            <div class="col-4">
              <strong>{{ key.replace('_', ' ').title() }}:</strong>
            </div>
            <div class="col-8">
              <input
                type="{% if 'PASSWORD' in key %}password{% else %}text{% endif %}"
                class="form-control"
                id="{{ key }}"
                value="{{ config_dict[key] }}" />
            </div>
          </li>
          {% endfor %}
        </ul>
      </div>

      <!-- Tarjeta de Base de Datos -->
      <div class="box">
        <h4 class="card-title">Base de Datos</h4>
        <hr />
        <ul class="list-unstyled">
          {% for key in ['USER_DB', 'PASSWORD_DB', 'SERVER', 'DATABASE_DB'] %}
          <li class="mb-2 row g-2 align-items-center">
            <div class="col-4">
              <strong>{{ key.replace('_', ' ').title() }}:</strong>
            </div>
            <div class="col-8">
              <input
                type="{% if 'PASSWORD' in key %}password{% else %}text{% endif %}"
                class="form-control"
                id="{{ key }}"
                value="{{ config_dict[key] }}" />
            </div>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

  <div class="text-center mt-4">
    <button type="submit" class="btn btn-primary mb-3">Guardar</button>
  </div>
</form>
{% endblock %} {% block extra_js %}
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
{% endblock %}

templates/home.html
{% extends 'index.html' %}
{% block title %}
  Inicio - eA3SC
{% endblock %}

{% block content %}
<div class="container mt-4">
  <h1>Información del Sistema</h1> <hr>
  <ul>
    <li>
      <strong>Versión:</strong> {{ VERSION }}
    </li>
    <li>
      <strong>Plataforma:</strong> {{ PLATFORM }}
    </li>
    <li>
      <strong>Directorio de Instalación:</strong> {{ PATH }}
    </li>
    <li>
      <strong>Archivo de configuración:</strong> {{ CONFIG_PATH }}
    </li>
    <li>
      <strong>Archivo de Logs:</strong> {{ LOGS }}
    </li>
  </ul>
</div>
{% endblock %}
{% block extra_js %}

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        eA3SC
      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet" />
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" />
    {% block extra_css %}

    {% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <ul class="navbar-brand mt-2">eA3SC</ul>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('app_blueprint.home') }}">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('app_blueprint.get_settings') }}">Configuración</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('app_blueprint.printer') }}">Imprimir</a>
          </li>
        </ul>
      </div>
    </nav>

  <main>
    {% block content %}
    {% endblock %}
  </main>

    {% block extra_js %}

    {% endblock %}

    <footer>
      © 2025 JNC. Todos los derechos reservados.
      <br>
      Desarrollado por jnc@jnc.es
    </footer>
  </body>
</html>

templates/print.html
{% extends 'index.html' %} {% block title %} Impresión - ePrint {% endblock %}
{% block content %}
<h1 class="title mt-4 text-center">Impresión</h1><hr>
<br/>
<div class="container">
<form id="print" class="d-flex flex-column">
  <div class="mb-3">
    <label for="printerSelect" class="form-label">Seleccionar impresora:</label>
    <select
      id="printerSelect"
      name="printer"
      class="form-select"
      required
    ></select>
  </div>
  <div class="mb-3">
    <label for="copiesNumber" class="form-label">Número de copias:</label>
    <input
      name="copies"
      required
      type="number"
      id="copiesNumber"
      value="1"
      min="1"
      max="10"
      class="form-control"
    />
  </div>
  <div class="mb-3">
    <label for="formatField" class="form-label"
      >Elige el archivo a imprimir:</label
    >
    <input
      name="format"
      required
      type="file"
      id="formatField"
      class="form-control"
      accept=".pdf,.zpl"
    />
  </div>
  <fieldset class="mb-3" id="printModeField">
    <legend class="h6">Modo de impresión</legend>
    <div class="form-check">
      <input
        type="radio"
        required
        name="driver"
        id="r1"
        value="Una cara"
        class="form-check-input"
        checked
      />
      <label for="r1" class="form-check-label">Una cara</label>
    </div>
    <div class="form-check">
      <input
        type="radio"
        name="driver"
        id="r2"
        value="2"
        class="form-check-input"
      />
      <label for="r2" class="form-check-label">Doble cara</label>
    </div>
  </fieldset>
  <div class="form-group">
    <label for="dpi">DPI</label>
    <input
      name="dpi"
      required
      disabled= true
      type="number"
      id="dpi"
      min="203"
      max="600"
      class="form-control"
    />
    
  </div>
  <button type="submit" class="btn btn-primary">Enviar</button>
</form>
</div>
{% endblock %} {% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
{% endblock %}